### ISSUE TITLE
Several Regex Patterns for one Attribute

### ISSUE THREAD

**Issue by sebbader-sap** [admin-shell-io/aas-specs#613]
# What?

Several `pattern` declarations are defined for an individual attribute, e.g. https://app.swaggerhub.com/domains/Plattform_i40/Part1-MetaModel-Schemas/V3.0#/components/schemas/AdministrativeInformation `version`:

```
    AdministrativeInformation:
      allOf:
      - "$ref": "#/components/schemas/HasDataSpecification"
      - properties:
          version:
            type: string
            allOf:
            - minLength: 1
              maxLength: 4
            - pattern: "^([\\t\\n\\r -\ud7ff\ue000-\ufffd]|\\ud800[\\udc00-\\udfff]|[\\ud801-\\udbfe][\\udc00-\\udfff]|\\udbff[\\udc00-\\udfff])*$"
            - pattern: "^(0|[1-9][0-9]*)$"
```

Generators ignore the `pattern` then.

# How?

Only declare the "most restrictive" pattern.

This issue relates to finding `DFKI#03`.
